#requires -Version 5.1
<#
  vault-status.ps1 - regenerate Ganesha\notes\worktrees.md: one page showing where every story is.

  Written for the case where the Ganesha folder itself is opened as an Obsidian vault, so the
  per-app deep-dives and this status page are notes without anything being copied or duplicated.
  Everything here is DERIVED (registry + ledgers + blocker check), so the file is disposable -
  regenerate it, never hand-edit it.

  notes\ lives OUTSIDE every repo, so it can never become a remove-worktree.ps1 blocker.

  Usage: vault-status.ps1 [-Out <path>] [-NoCheck] [-Json]
    -NoCheck  skip the git blocker scan (faster; the 'Clean' column reads 'not checked')
#>
[CmdletBinding()]
param(
  [string]$Out,
  [switch]$NoCheck,
  [switch]$Json,
  [string]$Root,  # override (native-host\host.ps1 / a Settings-driven root); blank = auto-resolve
  [string]$Project  # resolved project id (native-host\host.ps1); blank = active project / legacy resolution
)

$ErrorActionPreference = 'Stop'

Import-Module (Join-Path $PSScriptRoot 'stg-paths.psm1') -Force -DisableNameChecking
$Paths = Resolve-StgPaths -Root $Root -Project $Project
if ($Paths.NeedsSetup) {
  if ($Json) { [Console]::Out.Write((@{ ok = $false; error = $Paths.Error; needsSetup = $true } | ConvertTo-Json -Compress)) }
  else { Write-Host $Paths.Error -ForegroundColor Red }
  exit 0
}
$Root = $Paths.Root
# Tracking mode has no worktrees to blocker-scan at all - force the same skip -NoCheck already
# produces, rather than teaching the -CheckAll call below its own mode branch.
if ($Paths.Mode -eq 'tracking') { $NoCheck = $true }
Import-Module (Join-Path $PSScriptRoot 'StoryLib.psm1') -Force -DisableNameChecking

# Mirror of $DefaultPhases' grouping in story-ledger.ps1 - keep the two in sync (same rule
# popup.js's own PHASE_GROUPS comment states; this copy just never had the comment before).
$Groups = @(
  @{ name = 'Story Up'; phases = @('bring-up') }
  @{ name = 'Dev Loop'; phases = @('plan', 'implement', 'testplan', 'verify', 'typecheck', 'commit-push') }
  @{ name = 'Release';  phases = @('deploy') }
)
$Closed = @('done', 'skipped')

function Get-Glyph([string]$s, [bool]$isNext) {
  switch ($s) { 'done' { '[x]' } 'failed' { '[!]' } 'skipped' { '[-]' } 'running' { '[>]' }
    default { if ($isNext) { '[>]' } else { '[ ]' } } }
}

$result = [ordered]@{ ok = $true; output = $null; stories = 0; summary = '' }

try {
  $reg = Read-Registry -Root $Root -DocsDir $Paths.DocsDir
  # Get-StgNames, not the bare @($reg.stories.PSObject.Properties.Name) idiom - on an empty {}
  # registry that expression is $null, and @($null) is a one-element array HOLDING $null. The
  # Join-Path calls this used to feed degraded harmlessly on that null key, but Get-StgLedgerPath's
  # -Story is a Mandatory [string] parameter and throws "Cannot bind argument ... because it is an
  # empty string" on it instead - this surfaced the pre-existing bug as a hard crash on a fresh
  # install with zero stories (same root cause the 'apps' action's identical comment describes).
  $keys = Get-StgNames $reg.stories

  # One git scan for every story (the same call the extension's badges use).
  $checks = @{}
  if (-not $NoCheck) {
    # Sibling in tools\, not $Root - remove-worktree.ps1 travels with the scripts, not the data.
    $rw = Join-Path $PSScriptRoot 'remove-worktree.ps1'
    if (Test-Path $rw) {
      try {
        # [string]$Paths.ProjectId - see story-status.ps1's Get-LedgerNext for why the cast matters.
        $raw = & powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $rw -CheckAll -Root $Root -Project ([string]$Paths.ProjectId) -Json
        $parsed = ("$raw".Trim() | ConvertFrom-Json)
        if ($parsed -and $parsed.stories) {
          foreach ($p in $parsed.stories.PSObject.Properties) { $checks[$p.Name] = $p.Value }
        }
      }
      catch { }
    }
  }

  $L = @()
  $L += '# Worktrees'
  $L += ''
  $L += "_Generated by ``tools\vault-status.ps1`` on $(Get-Stamp). Derived from stories.json + each story's ledger - regenerate it, do not hand-edit._"
  $L += ''

  # Summary table first, so the page answers "what am I working on" in one glance.
  $L += '| Story | Env | Phase | Clean | Apps |'
  $L += '|---|---|---|---|---|'
  foreach ($k in $keys) {
    $node = $reg.stories.$k
    $ledPath = Get-StgLedgerPath -Paths $Paths -Story $k -Node $node
    $phaseCell = 'no ledger'
    if (Test-Path -LiteralPath $ledPath) {
      $led = $null; try { $led = Read-JsonFile -Path $ledPath } catch { }
      if ($led) {
        $ph = @($led.phases)
        $lastClosed = -1
        for ($i = 0; $i -lt $ph.Count; $i++) { if ($ph[$i].status -in $Closed) { $lastClosed = $i } }
        $next = $null
        for ($i = $lastClosed + 1; $i -lt $ph.Count; $i++) { if ($ph[$i].status -notin $Closed) { $next = $ph[$i].name; break } }
        $grp = $null
        foreach ($g in $Groups) { if ($next -and $g.phases -contains $next) { $grp = $g; break } }
        if ($grp) {
          $mine = @($ph | Where-Object { $grp.phases -contains $_.name })
          $done = @($mine | Where-Object { $_.status -in $Closed }).Count
          $phaseCell = "$($grp.name) $done/$($mine.Count) (next: $next)"
        }
        else { $phaseCell = 'all phases done' }
      }
    }
    # A shipped story must not keep reading as in-flight - that staleness is the whole reason the
    # released flag exists. The worktree is still on disk; only the reporting changes.
    if ("$($node.released)".Trim()) { $phaseCell = "RELEASED $($node.released)" }
    $ck = $checks[$k]
    # '-' for tracking mode (genuinely not applicable - no worktree, no apps concept), distinct
    # from 'not checked' (-NoCheck was passed, or the scan itself came back empty/failed).
    $cleanCell = if ($Paths.Mode -eq 'tracking') { '-' }
                 elseif ($NoCheck -or $null -eq $ck) { 'not checked' }
                 elseif ($ck.ok) { 'ready' }
                 else {
                   $n = 0; foreach ($b in @($ck.blockers)) { $n += @($b.dirty).Count }
                   $u = 0; foreach ($b in @($ck.blockers)) { $u += [int]$b.unpushed }
                   $bits = @(); if ($n) { $bits += "$n changed" }; if ($u) { $bits += "$u unpushed" }
                   if ($bits.Count) { $bits -join ', ' } else { 'blocked' }
                 }
    $appsCell = if ($Paths.Mode -eq 'tracking') { '-' } else { (@($node.apps | Where-Object { $_ })) -join ', ' }
    $L += "| [[$k]] | $($node.env) | $phaseCell | $cleanCell | $appsCell |"
  }
  $L += ''

  # Then one section per story: the full checklist + the identifiers worth clicking.
  foreach ($k in $keys) {
    $node = $reg.stories.$k
    $L += "## $k"
    $L += ''
    if ($node.title) { $L += "**$($node.title)**"; $L += '' }

    $facts = @()
    $facts += "env: ``$($node.env)``"
    $facts += "branch: ``$($node.branch)``"
    if ($node.rel) { $facts += "REL: [$($node.rel)](https://vesta.atlassian.net/browse/$($node.rel))" }
    if ($node.releaseBranch) { $facts += "release branch: ``$($node.releaseBranch)``" }
    if ("$($node.released)".Trim()) { $facts += "released: $($node.released)" }
    $chg = @(@($node.chg_number) + @(if ($node.chg_numbers) { $node.chg_numbers.PSObject.Properties.Value } else { @() }) | Where-Object { $_ })
    if ($chg.Count) { $facts += "CHG: $((@($chg | Select-Object -Unique)) -join ', ')" }
    # ASCII only in this source file: a BOM-less .ps1 is read as ANSI by PS 5.1, so a non-ASCII
    # literal here (a middle dot, an em dash) comes out double-encoded in the generated markdown.
    $L += ($facts -join ' | ')
    $L += ''

    $links = @()
    foreach ($u in @($node.jira_stories | Where-Object { $_ } | Select-Object -Unique)) { $links += "- Jira: $u" }
    # The singular field is usually ALSO one of the plural map's values - dedupe.
    foreach ($u in @(@($node.agiletest_url) + @(if ($node.agiletest_urls) { $node.agiletest_urls.PSObject.Properties.Value } else { @() }) | Where-Object { $_ } | Select-Object -Unique)) { $links += "- AgileTest: $u" }
    foreach ($p in @($node.PSObject.Properties | Where-Object { $_.Name -like 'document*' })) { if ($p.Value) { $links += "- Design note ($($p.Name)): $($p.Value)" } }
    if ($links.Count) { $L += $links; $L += '' }

    $ledPath = Get-StgLedgerPath -Paths $Paths -Story $k -Node $node
    if (Test-Path -LiteralPath $ledPath) {
      $led = $null; try { $led = Read-JsonFile -Path $ledPath } catch { }
      if ($led) {
        $ph = @($led.phases)
        $lastClosed = -1
        for ($i = 0; $i -lt $ph.Count; $i++) { if ($ph[$i].status -in $Closed) { $lastClosed = $i } }
        $next = $null
        for ($i = $lastClosed + 1; $i -lt $ph.Count; $i++) { if ($ph[$i].status -notin $Closed) { $next = $ph[$i].name; break } }
        $L += '```text'
        foreach ($g in $Groups) {
          $mine = @($ph | Where-Object { $g.phases -contains $_.name })
          if (-not $mine.Count) { continue }
          $done = @($mine | Where-Object { $_.status -in $Closed }).Count
          $detail = (@($mine | ForEach-Object { "$($_.name) $(Get-Glyph $_.status ($_.name -eq $next))" }) -join ' . ')
          $gGlyph = if (@($mine | Where-Object { $_.status -eq 'failed' }).Count) { '[!]' }
                    elseif ($done -eq $mine.Count) { '[x]' }
                    elseif (@($mine | Where-Object { $_.name -eq $next }).Count) { '[>]' }
                    else { '[ ]' }
          $L += ("{0} {1,-16} {2}" -f $gGlyph, "$($g.name) $done/$($mine.Count)", $detail)
        }
        $L += '```'
        $L += ''
        $L += if ($next) { "next: **$next**" } else { 'next: all phases done' }
        $L += ''
      }
    }
    else { $L += '_No ledger yet - run `tools\story-ledger.ps1 init -Story ' + $k + '`._'; $L += '' }

    $ck = $checks[$k]
    if ($ck -and -not $ck.ok) {
      $L += 'Blockers:'
      $L += ''
      foreach ($b in @($ck.blockers)) {
        $bits = @()
        if (@($b.dirty).Count) { $bits += "$(@($b.dirty).Count) changed: $((@($b.dirty)) -join ', ')" }
        if ($b.unpushed) { $bits += "$($b.unpushed) unpushed" }
        if ($b.noUpstream) { $bits += 'no upstream' }
        $L += "- ``$($b.app)`` - $($bits -join '; ')"
      }
      $L += ''
    }
  }

  # Tracking mode: $Root genuinely IS the tracked repo, so a bare <root>\notes\ folder would be
  # untracked clutter showing up in that repo's own `git status` - same reasoning as
  # Get-StgLedgerPath's own tracking-mode branch. Keep it under docsDir instead, consolidated with
  # every other tracking-mode artifact (stories.json, the per-story docs, ledgers).
  $notesDir = if ($Paths.Mode -eq 'tracking') { Join-Path (Join-Path $Root $Paths.DocsDir) 'notes' } else { Join-Path $Root 'notes' }
  if (-not (Test-Path -LiteralPath $notesDir)) { [void](New-Item -ItemType Directory -Path $notesDir -Force) }
  $outPath = if ($Out) { $Out } else { Join-Path $notesDir 'worktrees.md' }
  Write-Utf8NoBom -Path $outPath -Text (($L -join "`r`n") + "`r`n")

  $result.output = $outPath
  $result.stories = $keys.Count
  $result.summary = "wrote $outPath ($($keys.Count) stories)"

  if ($Json) { [Console]::Out.Write(($result | ConvertTo-Json -Depth 6 -Compress)); return }
  Write-Host ""
  Write-Host "  $($result.summary)" -ForegroundColor Green
  Write-Host ""
}
catch {
  $result.ok = $false
  $result.error = "vault-status error: $($_.Exception.Message)"
  if ($Json) { [Console]::Out.Write(($result | ConvertTo-Json -Depth 6 -Compress)) }
  else { Write-Host "`n$($result.error)`n" -ForegroundColor Red }
}
